direction: down

in0: in0.txt {style.font-color: "#888"}
in1: in1.txt {style.font-color: "#888"}
codegen: codegen.py {style.font-color: "#888"}

in0 -> codegen
in1 -> codegen

d: d.c / d.h (generated)
c: c.c / c.h (generated)
b: b.c / b.h (generated)
a: a.c / a.h (generated)

codegen -> d
codegen -> c
codegen -> b
codegen -> a

d -> c
d -> b
c -> a
b -> a
