direction: down

in0: in0.txt {style.font-color: "#888"}
in1: in1.txt {style.font-color: "#888"}
codegen: codegen.py {style.font-color: "#888"}

in0 -> codegen
in1 -> codegen

d: d.cpp | d (generated)
c: c.cpp | c (generated)
b: b.cpp | b (generated)
a: a.cpp | a (generated)

codegen -> d
codegen -> c
codegen -> b
codegen -> a

d -> c
d -> b
c -> a
b -> a
